version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html/src
      - ./backend/index.php:/var/www/html/index.php
    ports:
      - "8081:80" # Map host port to container port
    networks:
      - whatsphant
  
  db:
    container_name: db
    env_file:
      - ./_db/.env
    build:
      context: ./_db
      dockerfile: Dockerfile.bd
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - whatsphant

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - whatsphant

volumes: 
  dbdata:

networks:
  whatsphant:
    driver: bridge