version: '3'
services:
  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000" # Map host port to container port
    command: yarn dev
    depends_on:
      - backend

  backend:
    image: php:8.2.8-apache # You can choose the appropriate PHP version
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80" # Map host port to container port
