version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html/src
      - ./backend/index.php:/var/www/html/index.php
    ports:
      - "8081:80" # Map host port to container port
    networks:
      - whatsphant
  
networks:
  whatsphant:
    driver: bridge