# Use the latest MySQL image as the base
FROM mysql:latest

# Create a directory in the container to hold the SQL file
RUN mkdir -p /var/database

# Copy the database.sql file from the host into the container
COPY ./database.sql /var/database/